spring.application.name=found_item_service

server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5432/lost_found_db
spring.datasource.username=postgres
spring.datasource.password=7896

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.properties.hibernate.format_sql=true

spring.datasource.driver-class-name=org.postgresql.Driver

